[project]
name = "motor-controle"
version = "0.1.0"
requires-python = ">=3.11"
authors = [{ name = "Weslley Marcelo", email = "wessmarcelo@gmail.com" }]
description = "API de monitoramento em tempo real de motor"
readme = "README.md"
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "flask>=3.0.3",
    "flask_restx>=1.3.0",
    "gunicorn>=22.0.0",
    "gevent>=24.2.1",
    "python-dotenv>=1.0.0",
    "pymongo>=3.12.0",
    "flask-socketio>=5.2.0",
]

[project.optional-dependencies]
test = ["pytest>=7.0"]
docs = ["sphinx>=8.0.2", "furo>=2024.8.6"]
